architecture: replication
auth:
  rootPassword: ""
  database: my_database
  username: ""
  password: ""
  replicationUser: replicator
  replicationPassword: ""

primary:
  resources: {}
  persistence:
    enabled: true
    storageClass: ""
    accessModes:
      - ReadWriteOnce
    size: 8Gi

secondary:
  replicaCount: 1
  resources: {}
  persistence:
    enabled: true
    storageClass: ""
    accessModes:
      - ReadWriteOnce
    size: 8Gi

metrics:
  enabled: false
  resources: {}
  serviceMonitor:
    enabled: false
