apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-config
data:
  OWNCLOUD_DB_HOST: {{ .Release.Name }}-mysql
  OWNCLOUD_DB_NAME: {{ .Values.mysql.auth.database }}
  OWNCLOUD_DB_USERNAME: {{ .Values.mysql.auth.username }}
  OWNCLOUD_DB_TYPE: mysql
  OWNCLOUD_ADMIN_USERNAME: {{ .Values.ownCloud.adminUser }}
  OWNCLOUD_MAIL_DOMAIN: {{ .Values.ownCloud.mail.domain }}
  OWNCLOUD_MAIL_FROM_ADDRESS: {{ .Values.ownCloud.mail.fromAddress }}
  OWNCLOUD_MAIL_SMTP_AUTH: {{ .Values.ownCloud.mail.smtp.auth }}
  OWNCLOUD_MAIL_SMTP_HOST: {{ .Values.ownCloud.mail.smtp.host }}
  OWNCLOUD_MAIL_SMTP_MODE: {{ .Values.ownCloud.mail.mode }}
  OWNCLOUD_MAIL_SMTP_NAME: {{ .Values.ownCloud.mail.smtp.username }}
  OWNCLOUD_MAIL_SMTP_PORT: {{ .Values.ownCloud.mail.smtp.port }}
  OWNCLOUD_MAIL_SMTP_SECURE: {{ .Values.ownCloud.mail.smtp.secure }}
{{- with (index .Values.ingress.hosts 0) }}
  OWNCLOUD_DOMAIN: {{ .host }}
{{- end }}
  OWNCLOUD_MYSQL_UTF8MB4: "true"
  OWNCLOUD_REDIS_ENABLED: "true"
  OWNCLOUD_REDIS_HOST: {{ .Release.Name }}-redis
  OWNCLOUD_ACCESSLOG_LOCATION: "/dev/null"
  OWNCLOUD_DB_TIMEOUT: "30"
  OWNCLOUD_DAV_ENABLE_ASYNC: "1"
