apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secret
data:
  OWNCLOUD_DB_PASSWORD: {{ .Values.mariadb.auth.password | b64enc  }}
  OWNCLOUD_ADMIN_PASSWORD: {{ .Values.ownCloud.adminPassword | b64enc }}
  {{- if .Values.ownCloud.mail.smtp.password }}
  OWNCLOUD_MAIL_SMTP_PASSWORD: {{ .Values.ownCloud.mail.smtp.password | b64enc }}
  {{- end }}